SpotifyWrapper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')), # every url for user related templates will start with user/
    path('', include('mainApp.urls')) # all other urls are directed to the mainApp.urls file
]

mainApp/urls.py
from django.urls import path
from . import views
from .views import spotify_callback, IsAuthenticated

urlpatterns = [
    # Spotify authentication URLs
    path('get-auth-url', views.get_auth_url, name='auth_url'),
    path('redirect', spotify_callback),
    path('is-authenticated', IsAuthenticated.as_view(), name='is_authenticated'),

    # Main menu and wrap-related URLs
    path('main_menu/', views.main_menu, name='main_menu'),
    path('friend_request/', views.friend_request, name='friend_request'),
    path('act_on_friend_request/<int:invite_id>/<str:accepted>/', views.act_on_friend_request, name='act_on_friend_request'),
    path('create_new_single_wrap/', views.create_new_single_wrap, name='create_new_single_wrap'),

    # Single wrap viewing and management
    path('wrap/<int:wrap_id>/view/', views.single_wrap_view, name='wrap_view'),
    path('single_wrap/<int:wrap_id>/', views.single_wrap_view, name='single_wrap_view'),
    path('single_wrap/current/', views.single_wrap_view, name='wrap_current'),  # View the current wrap
    path('wrap/<int:wrap_id>/delete/', views.delete_wrap, name='wrap_delete'),  # Delete a single wrap

    # Duo wrap-related URLs
    path('duo_wrap/<int:duo_wrap_id>/', views.duo_wrap_view, name='duo_wrap'),
    path('duo_wrap/delete/<int:duo_wrap_id>/', views.delete_duo_wrap, name='duo_wrap_delete'),

    # Public and liked wraps
    path('public_wraps/', views.public_wraps, name='public_wraps'),
    path('liked_items/', views.liked_items_view, name='liked_items'),

    # Sharing, liking, and unliking wraps
    path('wrap/<int:wrap_id>/share/', views.share_wrap, name='share_wrap'),
    path('wrap/<int:wrap_id>/unshare/', views.unshare_wrap, name='unshare_wrap'),
    path('wrap/<int:wrap_id>/like/', views.like_wrap, name='like_wrap'),
    path('wrap/<int:wrap_id>/unlike/', views.unlike_wrap, name='unlike_wrap'),

    # Spotify playlist-related URLs
    path('spotify/like_playlist/', views.like_playlist, name='like_playlist'),

    # Contact page
    path('contact/', views.contact_view, name='contact'),
    ]

user/urls.py
# users/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [

    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('welcome/', views.welcome, name='welcome'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('delete_account/', views.delete_account, name='delete_account'),

]

mainApp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.utils import timezone


class Wrap(models.Model):
    THEME_CHOICES = [
        ('default', 'Default'),
        ('halloween', 'Halloween'),
        ('christmas', 'Christmas'),
    ]

    TERM_CHOICES = [
        ('short', 'Short-Term'),
        ('medium', 'Medium-Term'),
        ('long', 'Long-Term'),
    ]

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='wraps')
    name = models.CharField(max_length=100)
    term_type = models.CharField(max_length=10, choices=TERM_CHOICES, default='short')  # Added for term distinction
    top_artistsJSON = models.JSONField(null=True, blank=True, default=dict)
    top_songsJSON = models.JSONField(null=True, blank=True, default=dict)
    minutes_listened = models.IntegerField(default=0)
    top_genre = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    theme = models.CharField(max_length=10, choices=THEME_CHOICES, default='default')

    # New fields
    public = models.BooleanField(default=False)  # For sharing wraps
    likes = models.ManyToManyField(User, related_name='liked_wraps', blank=True)  # For tracking likes

    class Meta:
        unique_together = ('user', 'name', 'term_type')  # Updated to include term type

    def __str__(self):
        return f"{self.user.username}'s Wrap: {self.name} ({self.term_type}) (Created: {self.created_at.strftime('%Y-%m-%d')})"


class SpotifyToken(models.Model):
    """
    Model to store Spotify API tokens for a user.
    
    Attributes:
        user (OneToOneField): Reference to the user associated with the token.
        created_at (DateTimeField): Timestamp for when the token was created.
        refresh_token (CharField): Token used to refresh the access token.
        access_token (CharField): Token used to access Spotify API on behalf of the user.
        expires_in (DateTimeField): Expiration date and time of the access token.
        token_type (CharField): Type of token (e.g., Bearer).
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    refresh_token = models.CharField(max_length=150)
    access_token = models.CharField(max_length=150)
    expires_in = models.DateTimeField()
    token_type = models.CharField(max_length=50)



# Not needed for single wraps anymore
class TopArtist(models.Model):
    """
    Model to store the top artists for each wrap.

    Attributes:
        wrap (ForeignKey): Reference to the associated wrap.
        name (CharField): Name of the artist.
        rank (PositiveIntegerField): Ranking of the artist.
        image_url (URLField): URL to an image of the artist.
    """
    wrap = models.ForeignKey(Wrap, on_delete=models.CASCADE, related_name='top_artists')
    name = models.CharField(max_length=200)
    rank = models.PositiveIntegerField()
    image_url = models.URLField(blank=True)

    class Meta:
        ordering = ['rank']
        unique_together = ['wrap', 'rank']

    def __str__(self):
        return f"{self.name} (Rank {self.rank})"

# Not needed for single wraps anymore
class TopSong(models.Model):
    """"
    Model to store the top songs for each wrap.

    Attributes:
        wrap (ForeignKey): Reference to the associated wrap.
        title (CharField): Title of the song.
        artist (CharField): Name of the song's artist.
        rank (PositiveIntegerField): Ranking of the song.
        image_url (URLField): URL to an image of the song cover.
    """
    wrap = models.ForeignKey(Wrap, on_delete=models.CASCADE, related_name='top_songs')
    title = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    rank = models.PositiveIntegerField()
    image_url = models.URLField(blank=True)

    class Meta:
        ordering = ['rank']
        unique_together = ['wrap', 'rank']

    def __str__(self):
        return f"{self.title} by {self.artist} (Rank {self.rank})"


class DuoWrap(models.Model):
    user1 = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name='duo_wrap_user1'
    )
    user2 = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name='duo_wrap_user2'
    )
    wrap_name = models.CharField(max_length=100, default="Default Wrap")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    top_artists_comparison = models.JSONField(null=True, blank=True, default=dict)
    top_songs_comparison = models.JSONField(null=True, blank=True, default=dict)
    top_genre_comparison = models.JSONField(null=True, blank=True, default=dict)
    minutes_listened_comparison = models.JSONField(null=True, blank=True, default=dict)

    class Meta:
        unique_together = ('user1', 'user2', 'wrap_name')

    def __str__(self):
        return f"Duo Wrap: {self.user1.username} & {self.user2.username} ({self.wrap_name})"

    def get_top_artists_comparison(self):
        """
        Retrieve and compare top artists for both users.

        Returns:
            dict: Dictionaries containing artist comparison details.
        """
        user1_wrap = Wrap.objects.get(user=self.user1, name=self.wrap_name)
        user2_wrap = Wrap.objects.get(user=self.user2, name=self.wrap_name)

        user1_artists = user1_wrap.top_artists.all()
        user2_artists = user2_wrap.top_artists.all()

        return {
            'user1_top_artists': [
                {'name': artist.name, 'rank': artist.rank, 'image_url': artist.image_url}
                for artist in user1_artists
            ],
            'user2_top_artists': [
                {'name': artist.name, 'rank': artist.rank, 'image_url': artist.image_url}
                for artist in user2_artists
            ],
        }

    def get_top_songs_comparison(self):
        """
        Retrieve and compare top songs for both users.

        Returns:
            dict: Dictionaries containing song comparison details.
        """
        user1_wrap = Wrap.objects.get(user=self.user1, name=self.wrap_name)
        user2_wrap = Wrap.objects.get(user=self.user2, name=self.wrap_name)

        user1_songs = user1_wrap.top_songs.all()
        user2_songs = user2_wrap.top_songs.all()

        return {
            'user1_top_songs': [
                {'title': song.title, 'artist': song.artist, 'rank': song.rank, 'image_url': song.image_url}
                for song in user1_songs
            ],
            'user2_top_songs': [
                {'title': song.title, 'artist': song.artist, 'rank': song.rank, 'image_url': song.image_url}
                for song in user2_songs
            ],
        }

    def get_details(self):
        """
        Retrieve comprehensive details for the duo wrap.

        Returns:
            dict: Dictionary containing all comparison details.
        """
        return {
            'user1': self.user1,
            'user2': self.user2,
            'user1_top_artists': self.top_artists_comparison.get('user1', []),
            'user2_top_artists': self.top_artists_comparison.get('user2', []),
            'user1_top_songs': self.top_songs_comparison.get('user1', []),
            'user2_top_songs': self.top_songs_comparison.get('user2', []),
            'user1_top_genre': self.top_genre_comparison.get('user1', 'Unknown'),
            'user2_top_genre': self.top_genre_comparison.get('user2', 'Unknown'),
            'user1_minutes_listened': self.minutes_listened_comparison.get('user1', 0),
            'user2_minutes_listened': self.minutes_listened_comparison.get('user2', 0),
        }


class DuoWrap_Request(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    wrap_name = models.CharField(max_length=100)
    time_sent = models.DateTimeField(auto_now_add=True)
    request_accepted = models.BooleanField(default=False) #True if receiver accepts request
    request_denied = models.BooleanField(default=False) #True if receiver denies request

class Playlist(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="liked_playlists")
    spotify_id = models.CharField(max_length=50, unique=True)  # Spotify playlist ID
    name = models.CharField(max_length=255)  # Playlist name
    url = models.URLField()  # Spotify playlist URL

    def __str__(self):
        return f"{self.name} (by {self.user.username})"

mainApp/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.middleware import get_user
from django.contrib.auth.models import User
from django import forms
from django.dispatch import receiver
from django.forms.widgets import TextInput, PasswordInput, EmailInput
from .models import DuoWrap_Request, Wrap

class InviteFriendForm(forms.ModelForm):
    class Meta:
        model = DuoWrap_Request
        fields = ['receiver', 'wrap_name']
        labels = {
            'receiver': 'Friend\'s Username',
        }

    receiver = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label="Friend's Username"
    )

    wrap_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    # Makes form.is_valid() work by converting receiver text input into a User instance
    def clean_receiver(self):
        receiver_username = self.cleaned_data['receiver']

        try:
            receiver_user = User.objects.get(username=receiver_username)
        except User.DoesNotExist:
            raise forms.ValidationError("User with this username does not exist.")

        return receiver_user

    # Sets sender field as current User automatically when making a new DuoWrap_Request
    def save(self, commit=True, user=None):
        if user:
            self.instance.sender = user

        receiver_username = self.cleaned_data['receiver']
        try:
            receiver_user = User.objects.get(username=receiver_username)
            self.instance.receiver = receiver_user
        except User.DoesNotExist:
            raise forms.ValidationError("User with this username does not exist.")

        return super().save(commit=commit)


# Updated form to include term_type
class SingleWrapCreationForm(forms.Form):
    name = forms.CharField(
        max_length=255, 
        label="Wrap Name", 
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    term_type = forms.ChoiceField(
        choices=Wrap.TERM_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Term Type",
    )


class DuoWrapRequestForm(forms.ModelForm):
    """
    Form for creating a DuoWrap_Request, focusing on specifying the wrap name.
    """
    class Meta:
        model = DuoWrap_Request
        fields = ['wrap_name']
        labels = {
            'wrap_name': 'Duo Wrap Name',
        }

    wrap_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label="Duo Wrap Name"
    )

    def save(self, user, commit=True):
        """
        Custom save method to associate the sender with the request.

        Args:
            user (User): The user creating the request.
            commit (bool): Whether to commit the changes to the database.

        Returns:
            DuoWrap_Request: The saved DuoWrap_Request instance.
        """
        instance = super().save(commit=False)
        instance.sender = user
        if commit:
            instance.save()
        return instance

mainApp/templates/contact.html
{% load static %}

<!-- mainApp/templates/contact.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact the Developers</title>
    <link rel="stylesheet" href="{% static 'custom/custom.css' %}">
</head>
<body>
    <div class="container">
        <h1>Contact the Developers</h1>
        <p>If you have any questions, feedback, or issues, please contact us using the form below.</p>
        
        <!-- Existing contact form -->
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="subject">Subject:</label>
                <input type="text" id="subject" name="subject" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="message">Message:</label>
                <textarea id="message" name="message" rows="5" class="form-control" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Send Message</button>
        </form>

        <!-- New button linking to Google Form -->
        <div style="margin-top: 20px;">
            <a href="https://forms.gle/JhXqfc4znYAadYUA8" target="_blank">
                <button type="button" class="btn btn-secondary">Submit Form</button>
            </a>
        </div>
    </div>
</body>
</html>

mainApp/templates/create_new_single_wrap.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Single Wrap</title>
    <link rel="stylesheet" href="{% static 'custom/custom.css' %}">

    <style>
        /* Add extra spacing between sections */
        .section-spacing {
            margin-top: 30px;
            margin-bottom: 30px;
        }
        /* Ensure some padding at the bottom of the page */
        .page-end-spacing {
            padding-bottom: 50px;
        }
    </style>
</head>
<body>
<br><br><br>
<div class="row justify-content-center">
    <div class="col col-5">
        <div class="card shadow-lg">
            <div class="card-header text-center">Create a New Wrap</div>
            <div class="card-body">
    
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Create Wrap</button>
                </form>
                <button onclick="window.location.href='{% url 'main_menu' %}'" class="btn btn-secondary">Back to Main Menu</button>
                
            </div>
        </div>
    </div>
</div>

</body>
</html>

mainApp/templates/friend_requesting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Duo Wrap Friend Invite</title>
    <link rel="stylesheet" href="{% static 'custom/custom.css' %}">
    <!--<script src='{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}'></script>-->
</head>
<body>
<br>

<div class="container">
<br>
    <ul class="invite_list">
        {% for invite in invite_set %}
            <li>
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                    {{ invite.sender.username }} is requesting to make a Duo Wrap with you called {{ invite.wrap_name }}.

                    <button onclick="window.location.href='{% url 'act_on_friend_request' invite.id 'true' %}'" class="btn btn-sm btn-secondary">Accept</button>
                    <button onclick="window.location.href='{% url 'act_on_friend_request' invite.id 'false' %}'" class="btn btn-sm btn-primary" data-bs-dismiss="alert"> Deny</button>

                </div>

            </li>
            {% empty %}
            <p class="text-center">You have no pending invites</p>
        {% endfor %}
    </ul>

<br>
<div class="row justify-content-center">
    <div class="col col-6">
        <div class="card shadow-lg">
            <div class="card-header text-center">Send a Duo Wrap invite</div>
            <div class="card-body">

                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Send Friend Invite</button>
                </form>
                
                <button onclick="window.location.href='{% url 'main_menu' %}'" class="btn btn-secondary">Back to Main Menu</button>
                <br><br>
                <div>
                    The Duo Wrap will appear in your list of saved wraps on the main menu once your friend accepts the invite.
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

mainApp/templates/main_menu.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Menu</title>
    <link rel="stylesheet" href="{% static 'custom/custom.css' %}">

    <!-- Load holiday-specific styles if theme is set 
    {% if theme == "halloween" %}
        <link rel="stylesheet" href="{% static 'custom/halloween.css' %}">
    {% elif theme == "christmas" %}
        <link rel="stylesheet" href="{% static 'custom/christmas.css' %}">
    {% endif %}-->

    <style>
        /* Add extra spacing between sections */
        .section-spacing {
            margin-top: 30px;
            margin-bottom: 30px;
        }
        /* Ensure some padding at the bottom of the page */
        .page-end-spacing {
            padding-bottom: 50px;
        }
    </style>
</head>
<body class="page-end-spacing">

    <!-- style for header -->
<style>
    h3 {
        justify-content: center;
        font-size: 8rem;
        display: flex;
    }

    #music {
        color: #aaff00;
    }
    #wrap {
        color: #00fff8;
    }

</style>

<div class="container-fluid">
    <!-- header row -->
    <h3 class="justify-content-between text-center">
        <div class="col col-1">
            <img src="{% static 'images/Musicwrap_logo.png' %}" alt="Responsive Image" class="img-fluid">
        </div>
        <div class="d-flex">
            <div id="music">Music</div><div id="wrap">Wrap</div>
        </div>
        <div class="d-flex col-1"></div>

    </h3>

    <!-- Add holiday greeting -->
    {% if theme == "halloween" %}
        <h2 class="section-spacing" style="color: orange;">🎃 Happy Halloween! 🎃</h2>
    {% elif theme == "christmas" %}
        <h2 class="section-spacing" style="color: red;">🎄 Merry Christmas! 🎄</h2>
    {% endif %}


    <br>

    <div class="container">
        <!-- buttons row -->
        <div class="row section-spacing">
            <div class="col col-lg-2">
                <button onclick="window.location.href='{% url 'create_new_single_wrap' %}'" class="btn btn-secondary">Create a new Wrap</button>
            </div>
            <div class="col col-lg-2">
                <button onclick="window.location.href='{% url 'friend_request' %}'" class="btn btn-secondary">Create a new Duo Wrap</button>
            </div>
            <div class="col col-lg-5">
                <button onclick="window.location.href='{% url 'public_wraps' %}'" class="btn btn-primary">View Public Wraps</button>
            </div>
            <div class="col col-lg-1 ms-auto">
                <button onclick="window.location.href='{% url 'user:profile' %}'" class="btn btn-primary">Profile</button>
            </div>
            <div class="col col-lg-2">
                <button onclick="window.location.href='{% url 'contact' %}'" class="btn btn-secondary">Contact Developers</button>
            </div>
        </div>
    </div>




        <!-- Display Name -->
        <!--
        <div class="section-spacing">
            Display Name (From Your Spotify Account): <span id="displayName"></span>
        </div>-->

        <!-- Spotify Data Sections 
        <h2 class="section-spacing">Recently Played Tracks</h2>
        <ul class="list-group">
            {% for track in recent_tracks %}
                <li class="list-group-item">
                    {{ track.track.name }} by
                    {% for artist in track.track.artists %}
                        {{ artist.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </li>
            {% empty %}
                <li class="list-group-item">No recently played tracks available.</li>
            {% endfor %}
        </ul>
        
        <pre>{{ recent_tracks|safe }}</pre>
        -->

        <!--
        <h2 class="section-spacing">Top Artists</h2>
        <ul class="list-group">
            {% for artist in top_artists %}
                <li class="list-group-item">{{ artist.name }}</li>
            {% empty %}
                <li class="list-group-item">No top artists available.</li>
            {% endfor %}
        </ul>-->


        <!-- Spotify Wraps Section -->
        <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <h2 class="text-center">Your Spotify Wraps</h2>
        </li>
            {% for wrap in user_wraps %}
                <li id="wrap-{{ wrap.id }}" class="list-group-item list-group-item-action">
                    <div class="row align-items-center">
                        <!-- Wrap Name -->
                        <div class="col col-4">
                            <a href="{% url 'single_wrap_view' wrap.id %}">{{ wrap.name }}</a>
                        </div>
                        <!-- Date Created -->
                        <div class="col col-4">
                            Date Created: {{ wrap.created_at|date:"m/d/Y" }}
                        </div>
                        <div class="col col-2">
                            Type: {{ wrap.term_type }} term
                        </div>
                        <!-- Delete Button -->
                        <div class="col col-2 text-end">
                            <button class="btn btn-danger btn-sm" onclick="deleteWrap({{ wrap.id }})">Delete</button>
                        </div>
                    </div>
                </li>
            {% empty %}
                <li class="list-group-item text-center">No Wraps available.</li>
            {% endfor %}
        </ul>

        <br><br>

        <!-- Duo Wraps list -->
        <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <h2 class="text-center">Your Duo Wraps</h2>
        </li>
            {% for duo_wrap in duo_wraps %}
                <li id="duo-wrap-{{ duo_wrap.id }}" class="list-group-item list-group-item-action">
                    <div class="row align-items-center">
                        <!-- Duo Wrap Name -->
                        <div class="col col-4">
                            <a href="{% url 'duo_wrap' duo_wrap.id %}">{{ duo_wrap.wrap_name }}</a>
                        </div>
                        <!-- Date Created -->
                        <div class="col col-4">
                            Date Created: {{ duo_wrap.created_at|date:"m/d/Y" }}
                        </div>
                        <!-- Made With -->
                        <div class="col col-2">
                            Made with:
                            {% if duo_wrap.user1 == user %}
                                {{ duo_wrap.user2.username }}
                            {% else %}
                                {{ duo_wrap.user1.username }}
                            {% endif %}
                        </div>
                        <!-- Delete Button -->
                        <div class="col col-2 text-end">
                            <button class="btn btn-danger btn-sm" onclick="deleteDuoWrap({{ duo_wrap.id }})">Delete</button>
                        </div>
                    </div>
                </li>
            {% empty %}
                <li class="list-group-item text-center">No Duo Wraps available.</li>
            {% endfor %}
        </ul>

    <br><br>

    <h2 class="section-spacing text-center">Top Tracks</h2>
        <ul class="list-group">
            {% for track in top_tracks %}
                <li class="list-group-item">
                    {{ track.name }} by
                    {% for artist in track.artists %}
                        {{ artist.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                     Play and Pause buttons
                    <button onclick="playPreview('{{ track.preview_url }}', this)" class="play-btn btn btn-primary">Play</button>
                    <button onclick="pausePreview()" class="pause-btn btn btn-secondary" style="display:none;">Pause</button>
                </li>
            {% empty %}
                <li class="list-group-item">No top tracks available.</li>
            {% endfor %}
        </ul> 


    </div>
</div>

<!-- javascript -->
<script src="{% static 'js/script.js' %}"></script>
<script>
    authenticateSpotify();
    
    var profile = fetchProfile("{{ spotify_token.access_token }}");
    //console.log("Access token passed to fetchProfile:", "{{ spotify_token.access_token }}"); // Debug: print token in console

    function deleteWrap(wrapId) {
        if (confirm("Are you sure you want to delete this wrap?")) {
            fetch(`{% url 'wrap_delete' 0 %}`.replace('0', wrapId), {
                method: 'DELETE',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/json',
                },
            })
            .then(response => {
                if (response.ok) {
                    document.getElementById(`wrap-${wrapId}`).remove();
                } else {
                    alert("Failed to delete wrap.");
                }
            });
        }
    }

    let currentAudio = null;
let currentPlayButton = null;

function playPreview(url, playButton) {
    // If audio is already playing, pause it and reset buttons
    if (currentAudio) {
        currentAudio.pause();
        if (currentPlayButton) {
            currentPlayButton.style.display = 'inline';
            currentPlayButton.nextElementSibling.style.display = 'none';
        }
    }

    // Set the current button and audio
    currentPlayButton = playButton;
    currentAudio = new Audio(url);

    // Update button display
    playButton.style.display = 'none';  // Hide play button
    playButton.nextElementSibling.style.display = 'inline';  // Show pause button

    // Play audio
    currentAudio.play();
}

function pausePreview() {
    if (currentAudio) {
        currentAudio.pause();
        
        // Show play button and hide pause button
        if (currentPlayButton) {
            currentPlayButton.style.display = 'inline';
            currentPlayButton.nextElementSibling.style.display = 'none';
        }
    }
}

function deleteDuoWrap(duoWrapId) {
    if (confirm("Are you sure you want to delete this Duo Wrap?")) {
        fetch(`/duo_wrap/delete/${duoWrapId}/`, {
            method: 'DELETE',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}', // Ensure CSRF token is passed
                'Content-Type': 'application/json',
            },
        })
        .then(response => {
            if (response.ok) {
                // Remove the Duo Wrap from the DOM if the deletion is successful
                document.getElementById(`duo-wrap-${duoWrapId}`).remove();
            } else {
                alert("Failed to delete Duo Wrap.");
            }
        })
        .catch(error => {
            console.error("Error deleting Duo Wrap:", error);
            alert("An error occurred while deleting the Duo Wrap.");
        });
    }
}

    
</script>
</body>
</html>