SpotifyWrapper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')), # every url for user related templates will start with user/
    path('', include('mainApp.urls')) # all other urls are directed to the mainApp.urls file
]

user/urls.py
# users/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [

    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('welcome/', views.welcome, name='welcome'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('delete_account/', views.delete_account, name='delete_account'),

]

user/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class UserProfile(models.Model):

    """
    A model to store additional information about the user, specifically 
    an authentication status flag.

    Attributes:
        user: A one-to-one relationship to Django's built-in User model.
        is_authenticated: A boolean field indicating whether the user is 
                          authenticated, defaulting to False.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_authenticated = models.BooleanField(default=False)

    def __str__(self):
        """
        Returns the username of the associated User as the string representation 
        of the UserProfile instance.
        """
        return self.user.username

user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.forms.widgets import TextInput, PasswordInput, EmailInput


class CreateUserForm(UserCreationForm):

    """
    A form for creating new users. Extends Django's UserCreationForm to include fields 
    for first name, last name, username, email, and password with custom form controls.

    Fields:
        - first_name: Required field for user's first name.
        - last_name: Required field for user's last name.
        - username: Required field for unique username.
        - email: Required field for user's email address.
        - password1: Required field for user's password.
        - password2: Required field for confirming user's password.

    Meta:
        model: Specifies the User model associated with this form.
        fields: Lists the fields to include in the form, namely first name, last name, 
                username, email, password1, and password2.
    """
    max_length = {
        'first_name': 150,
        'last_name': 150,
        'username': 150,
        'email': 150,
        'password1': 150,
        'password2': 150,
    }
    first_name = forms.CharField(
        required=True,
        widget=TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField(
        required=True,
        widget=TextInput(attrs={'class': 'form-control'})
    )
    username = forms.CharField(
        required=True,
        widget=TextInput(attrs={'class': 'form-control'})
    )
    email = forms.EmailField(
        required=True,
        widget=EmailInput(attrs={'class': 'form-control'})
    )
    password1 = forms.CharField(
        required=True,
        widget=PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        required=True,
        widget=PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):

    """
    A form for authenticating users. Extends Django's AuthenticationForm to include 
    username and password fields with custom form controls.

    Fields:
        - username: Required field for user's username, displayed as a text input with custom styling.
        - password: Required field for user's password, displayed as a password input with custom styling.
    """
    username = forms.CharField(max_length=100, widget=TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=100, widget=PasswordInput(attrs={'class': 'form-control'}))

user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . forms import CreateUserForm, LoginForm


# Authentication models and functions
from django.contrib.auth.models import auth


# Create your views here.

def register(request):

    """
    Handle user registration by displaying and processing the registration form.

    If the request method is POST and the form is valid, the new user is created,
    and the user is redirected to the login page. Otherwise, an empty registration
    form is displayed.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Renders the registration page with the registration form.
    """

    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('user:login')

    context = {'registerForm':form}

    return render(request, 'register.html', context)



def login(request):

    """
    Handle user login by displaying and processing the login form.

    If the request method is POST and the form is valid, the user is authenticated
    and logged in, then redirected to the main menu. Otherwise, an empty login form
    is displayed.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Renders the login page with the login form.
    """

    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)

        if form.is_valid():
            # Gets data that user put into login page
            username = request.POST.get('username')
            password = request.POST.get('password')

            # Checks to see if inputted data is equal to a user
            user = auth.authenticate(request, username=username, password=password)

            # If user with that data exists, then login and go to main_menu
            if user is not None:
                auth.login(request, user)
                return redirect('main_menu')

    context = {'loginform':form}
    return render(request, 'login.html', context)


def profile(request):
    """
    Display the user profile page.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Renders the profile page with the user's information.
    """
    context = {
        'user': request.user,
    }
    return render(request, 'profile.html', context)

def welcome(request):
    """
    Display the welcome page.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Renders the welcome page.
    """
    return render(request, 'welcome.html')

def logout(request):
    """
    Log out the current user and redirect to the welcome page.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Redirects to the welcome page after logging out.
    """
    auth.logout(request)
    return redirect('user:welcome')

def delete_account(request):
    """
    Delete the authenticated user's account after logging them out.

    If the user is authenticated, they are logged out, and their account is deleted,
    then redirected to the main menu. If the user is not authenticated, they are
    redirected to the login page.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Redirects to the main menu or login page based on authentication status.
    """
    if request.user.is_authenticated:
        user = request.user
        logout(request)  # Log the user out before deleting their account
        user.delete()  # Delete the user
        return redirect('main_menu')
    else:
        return redirect('user:login')  # Redirect to login if not authenticated

user/templates/login.html
<!-- user/templates/login.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'custom/custom.css' %}">
</head>
<body>



<div class="container mt-5">
    <br><br><br><br><br>
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card shadow-lg">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <!-- error messages-->
                        {{ loginform.non_field_errors }}

                        <!-- Username Field -->
                        <label for="{{ loginform.username.id_for_label }}" class="label">Username</label>
                        {{ loginform.username }}
                        {{ loginform.username.errors }}

                        <!-- Password Field -->
                        <label for="{{ loginform.password.id_for_label }}" class="label">Password</label>
                        {{ loginform.password }}
                        {{ loginform.password.errors }}

                        <!-- Login Button -->
                        <div class="d-grid gap-2 mt-3">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>

                    <!-- Register Button -->
                    <div class="d-grid gap-2 mt-3">
                        <a href="{% url 'user:register' %}" class="btn btn-secondary">Register</a>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
</body>
</html>

user/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'custom/custom.css' %}">
</head>
<body>

<div class="container mt-5">
    <br><br><br><br><br>
    <div class="row text-center justify-content-center">
        <h1>Welcome to your Profile, {{ user.username }}!</h1>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card shadow-lg border-secondary">
                <div class="card-body">
                    <p>Username: {{ user.username }}</p>
                    <p>Firstname: {{user.first_name}}</p>
                    <p>Lastname: {{user.last_name}}</p>
                    <p>Email: {{ user.email }}</p>

                    <button onclick="window.location.href='{% url 'user:logout' %}'" class="btn btn-primary">Logout</button>
                    <button onclick="window.location.href='{% url 'main_menu' %}'" class = "btn btn-secondary">Back to Main Menu</button>
                    <button onclick="window.location.href='{% url 'user:delete_account' %}'" class="btn btn-primary">Delete Account</button>

                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

user/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'custom/custom.css' %}">
</head>
<body>

<div class="container mt-5">
    <br><br><br><br><br>
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h1 class="text-center">Register Here</h1>
                    <form method="post" autocomplete="off">
                        {% csrf_token %}
                        <!-- Form errors-->
                        {{ registerForm.non_field_errors }}

                        <!-- First Name Field -->
                        <div class="form-group mb-3">
                            <label for="{{ registerForm.first_name.id_for_label }}" class="label d-block">First Name</label>
                            {{ registerForm.first_name }}
                            {{ registerForm.first_name.errors }}
                        </div>

                        <!-- Last Name Field -->
                        <div class="form-group mb-3">
                            <label for="{{ registerForm.last_name.id_for_label }}" class="label d-block">Last Name</label>
                            {{ registerForm.last_name }}
                            {{ registerForm.last_name.errors }}
                        </div>

                        <!-- Username Field -->
                        <div class="form-group mb-3">
                            <label for="{{ registerForm.username.id_for_label }}" class="label d-block">Username</label>
                            {{ registerForm.username }}
                            {{ registerForm.username.errors }}
                        </div>

                        <!-- Email Field -->
                        <div class="form-group mb-3">
                            <label for="{{ registerForm.email.id_for_label }}" class="label d-block">Email</label>
                            {{ registerForm.email }}
                            {{ registerForm.email.errors }}
                        </div>

                        <!-- Password Field -->
                        <div class="form-group mb-3">
                            <label for="{{ registerForm.password1.id_for_label }}" class="label d-block">Password</label>
                            {{ registerForm.password1 }}
                            {{ registerForm.password1.errors }}
                        </div>

                        <!-- Confirm Password Field -->
                        <div class="form-group mb-3">
                            <label for="{{ registerForm.password2.id_for_label }}" class="label d-block">Confirm Password</label>
                            {{ registerForm.password2 }}
                            {{ registerForm.password2.errors }}
                        </div>

                        <!-- Register Button -->
                        <div class="d-grid gap-2 mt-3">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </form>

                    <!-- Login Button -->
                    <div class="d-grid gap-2 mt-3">
                        <a href="{% url 'user:login' %}" class="btn btn-secondary">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

user/templates/welcome.html
<!-- user/templates/welcome.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
    <link rel="stylesheet" href="{% static 'custom/custom.css' %}">
</head>
<body>
    <div class="container text-center">
        <div class="row justify-content-center">
            <div class="col-md-3">
                <br><br>
                <img src="{% static 'images/Musicwrap_logo_with_name.png' %}" alt="Responsive Image" class="img-fluid">
                <div class="row justify-content-center">
                    <p>Find your vibe.</p>
                <div class="col d-grid gap-2">
                    <button onclick="window.location.href='{% url 'user:login' %}'" class="btn btn-primary btn-lg">Login</button>
                </div>
                <div class="col d-grid gap-2">
                    <button onclick="window.location.href='{% url 'user:register' %}'" class="btn btn-secondary btn-lg">Register</button>
                </div>
            </div>
            </div>
        </div>
    </div>
</body>
</html>